{
 "title": "containerSSH-Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Gateway-VM Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / 3600", "type": "math" }
   ]
  },
  {
   "title": "Containers on Gateway",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\", instance=\"gateway-vm:8088\"})"
    },
    {}
   ]
  },
  {
   "title": "VMs Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"gateway-vm:9100\"} - (node_memory_MemFree_bytes{instance=\"gateway-vm:9100\"} + node_memory_Cached_bytes{instance=\"gateway-vm:9100\"} + node_memory_Buffers_bytes{instance=\"gateway-vm:9100\"})",
     "legendFormat": "Gateway-VM"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"sacrificial-vm:9100\"} - (node_memory_MemFree_bytes{instance=\"sacrificial-vm:9100\"} + node_memory_Cached_bytes{instance=\"sacrificial-vm:9100\"} + node_memory_Buffers_bytes{instance=\"sacrificial-vm:9100\"})",
     "legendFormat": "Sacrificial-VM"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"logger-vm:9100\"} - (node_memory_MemFree_bytes{instance=\"logger-vm:9100\"} + node_memory_Cached_bytes{instance=\"logger-vm:9100\"} + node_memory_Buffers_bytes{instance=\"logger-vm:9100\"})",
     "legendFormat": "Logger-VM"
    }
   ]
  },
  {
   "title": "Containers: Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=~\".+\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Logger-VM Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / 3600", "type": "math" }
   ]
  },
  {
   "title": "Containers on Logger",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\", instance=\"logger-vm:8088\"})"
    },
    {}
   ]
  },
  {
   "title": "Containers: Transmit Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=~\".+\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sacrificial-VM Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / 3600", "type": "math" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\"})"
    }
   ]
  },
  {
   "title": "VMs RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_Active_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Container's Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}