{
 "title": "containerSSH-Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "VMs Status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"gateway-vm:9100\"}",
     "legendFormat": "Gateway-VM"
    },
    {
     "expr": "up{instance=\"logger-vm:9100\"}",
     "legendFormat": "Logger-VM"
    },
    {
     "expr": "up{instance=\"sacrificial-vm:9100\"}",
     "legendFormat": "Sacrificial-VM"
    }
   ]
  },
  {
   "title": "Gateway-VM Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / 3600", "type": "math" }
   ]
  },
  {
   "title": "Containers on Gateway",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\", instance=\"gateway-vm:8088\"})"
    },
    {}
   ]
  },
  {
   "title": "VM Disk Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{fstype=\"ext4\", instance=\"gateway-vm:9100\"}-node_filesystem_avail_bytes{fstype=\"ext4\", instance=\"gateway-vm:9100\"}) / node_filesystem_size_bytes{fstype=\"ext4\", instance=\"gateway-vm:9100\"}) * 100",
     "legendFormat": "Gateway-VM"
    },
    {
     "expr": "((node_filesystem_size_bytes{fstype=\"ext4\", instance=\"logger-vm:9100\"}-node_filesystem_avail_bytes{fstype=\"ext4\", instance=\"logger-vm:9100\"}) / node_filesystem_size_bytes{fstype=\"ext4\", instance=\"logger-vm:9100\"}) * 100",
     "legendFormat": "Logger-VM"
    },
    {
     "expr": "((node_filesystem_size_bytes{fstype=\"ext4\", instance=\"sacrificial-vm:9100\"}-node_filesystem_avail_bytes{fstype=\"ext4\", instance=\"sacrificial-vm:9100\"}) / node_filesystem_size_bytes{fstype=\"ext4\", instance=\"sacrificial-vm:9100\"}) * 100",
     "legendFormat": "Sacrificial-VM"
    }
   ]
  },
  {
   "title": "VM Memory Usage  Percentage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"gateway-vm:9100\"} - node_memory_MemAvailable_bytes{instance=\"gateway-vm:9100\"}) / node_memory_MemTotal_bytes{instance=\"gateway-vm:9100\"} * 100",
     "legendFormat": "Gateway-VM"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"logger-vm:9100\"} - node_memory_MemAvailable_bytes{instance=\"logger-vm:9100\"}) / node_memory_MemTotal_bytes{instance=\"logger-vm:9100\"} * 100",
     "legendFormat": "Logger-VM"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"sacrificial-vm:9100\"} - node_memory_MemAvailable_bytes{instance=\"sacrificial-vm:9100\"}) / node_memory_MemTotal_bytes{instance=\"sacrificial-vm:9100\"} * 100",
     "legendFormat": "Sacrificial-VM"
    }
   ]
  },
  {
   "title": "Containers: Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=~\".+\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Logger-VM Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / 3600", "type": "math" }
   ]
  },
  {
   "title": "Containers on Logger",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\", instance=\"logger-vm:8088\"})"
    },
    {}
   ]
  },
  {
   "title": "Containers: Transmit Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=~\".+\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sacrificial-VM Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / 3600", "type": "math" }
   ]
  },
  {
   "title": "Containers on Sacrificial",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\", instance=\"sacrificial-vm:8088\"})"
    }
   ]
  },
  {
   "title": "VM Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=\"ext4\", instance=\"gateway-vm:9100\"}-node_filesystem_avail_bytes{fstype=\"ext4\", instance=\"gateway-vm:9100\"}",
     "legendFormat": "Gateway-VM"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype=\"ext4\", instance=\"logger-vm:9100\"}-node_filesystem_avail_bytes{fstype=\"ext4\", instance=\"logger-vm:9100\"}",
     "legendFormat": "Logger-VM"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype=\"ext4\", instance=\"sacrificial-vm:9100\"}-node_filesystem_avail_bytes{fstype=\"ext4\", instance=\"sacrificial-vm:9100\"}",
     "legendFormat": "Sacrificial-VM"
    }
   ]
  },
  {
   "title": "VM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"gateway-vm:9100\"} - node_memory_MemAvailable_bytes{instance=\"gateway-vm:9100\"}",
     "legendFormat": "Gateway-VM"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"logger-vm:9100\"} - node_memory_MemAvailable_bytes{instance=\"logger-vm:9100\"}",
     "legendFormat": "Logger-VM"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"sacrificial-vm:9100\"} - node_memory_MemAvailable_bytes{instance=\"sacrificial-vm:9100\"}",
     "legendFormat": "Sacrificial-VM"
    }
   ]
  },
  {
   "title": "Container's Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}