# Modified based on prometheus' official example config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  # expose node exporter metrics
  - job_name: "nodeexporter-gateway-vm"
    static_configs:
      - targets: ["gateway-vm:9100"]
  
  # expose node exporter metrics
  - job_name: "nodeexporter-logger-vm"
    static_configs:
      - targets: ["logger-vm:9100"]
  
  # expose node exporter metrics
  - job_name: "nodeexporter-sacrificial-vm"
    static_configs:
      - targets: ["sacrificial-vm:9100"]
  
  # expose cadvisor metrics
  - job_name: "cadvisor-container-on-gateway-vm"
    static_configs:
      - targets: ["gateway-vm:8088"]

  # expose cadvisor metrics
  - job_name: "cadvisor-container-on-logger-vm"
    static_configs:
      - targets: ["logger-vm:8088"]

  # expose cadvisor metrics
  - job_name: "cadvisor-container-on-sacrificial-vm"
    static_configs:
      - targets: ["sacrificial-vm:8080"]
